CREATE
DATABASE voltrent
    WITH OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    TEMPLATE template0;


-- USERS TABLE
CREATE TABLE users
(
    id         UUID         NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    email      VARCHAR(255) NOT NULL,
    fullname   VARCHAR(255),
    password   VARCHAR(255) NOT NULL,
    phone      VARCHAR(255),
    role       VARCHAR(255),
    PRIMARY KEY (id)
);


ALTER TABLE users
    ADD CONSTRAINT UK6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- VEHICLES TABLE
CREATE TABLE vehicles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    image_url      VARCHAR(255),
    is_paused      BOOLEAN      NOT NULL,
    latitude       FLOAT(53),
    longitude      FLOAT(53),
    name           VARCHAR(255) NOT NULL,
    owner_email    VARCHAR(255) NOT NULL,
    owner_id       UUID         NOT NULL,
    price_per_hour FLOAT(53)    NOT NULL,
    status         VARCHAR(255) NOT NULL CHECK (status IN ('AVAILABLE', 'PAUSED', 'RENTED', 'MAINTENANCE')),
    type           VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- VEHICLES indexes
CREATE INDEX idx_type ON vehicles (type);
CREATE INDEX idx_price ON vehicles (price_per_hour);
CREATE INDEX idx_owner ON vehicles (owner_id);

-- BOOKINGS TABLE
CREATE TABLE bookings
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at             TIMESTAMP(6) WITH TIME ZONE,
    updated_at             TIMESTAMP(6) WITH TIME ZONE,
    end_time               VARCHAR(255),
    payment_completed_time TIMESTAMP(6),
    start_time             VARCHAR(255),
    status                 VARCHAR(255),
    total_amount           FLOAT(53),
    user_id                UUID NOT NULL,
    vehicle_id             VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- BOOKINGS index for fast time-based search
CREATE INDEX idx_booking_time ON bookings (vehicle_id, start_time, end_time);

-- PAYMENTS TABLE
CREATE TABLE payments
(
    id               BIGINT       NOT NULL,
    created_at       TIMESTAMP(6) WITH TIME ZONE,
    updated_at       TIMESTAMP(6) WITH TIME ZONE,
    booking_id       VARCHAR(255) NOT NULL,
    gateway          VARCHAR(255),
    partner_code     VARCHAR(255),
    partner_pay_date VARCHAR(255),
    status           VARCHAR(255),
    total_amount     FLOAT(53)    NOT NULL,
    transaction_ref  VARCHAR(255),
    PRIMARY KEY (id)
);


