name: Build and Deploy to EC2   # Name of the workflow

# --------------------------------------------------
# Trigger: runs only when you push or merge into master
# --------------------------------------------------
on:
  push:
    branches:
      - master

# --------------------------------------------------
# Define a job — each job runs in its own environment
# --------------------------------------------------
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest    # GitHub-hosted runner (Ubuntu VM)

    steps:
      # Step 1: Checkout your code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Java (required for Maven and Jib)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin


      # Step 4: Build and push Docker image using Jib
      - name: Build and push image with Jib
        run: mvn -B clean compile jib:build

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-deploy   # 👈 this ensures job runs *after* image build

    steps:
      - name: SSH into EC2 and update containers
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker compose pull
            sudo docker compose up -d